name: Base Image build

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/base_image_push.yaml
      - Dockerfile_base

jobs:
  build:
    name: Build base image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Push to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          dockerfile: Dockerfile_base
          name: keycap-archivist/app/base
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tags: "latest"
      - name: Dispatch "base_image_build"
        run: |
          curl -X POST https://api.github.com/repos/keycap-archivist/app/dispatches \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            --data '{"event_type": "base_image_build"}'
